apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: sjm-py-tastpa-206
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sjm-py-tastpa-206 
  name: sjm-py-tastpa-206
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sjm-py-tastpa-206
    weight: 100 
